name: Keithley 2100
read_termination: "\n"
commands:
  set_reset:
    method: write
    message: "*RST"
sequences:
  do_reset:
    - set_reset: []
errors:
  expression: Error\:\s*(\-?\d+)
  messages:
  -101: Invalid character
  -102: Syntax error
  -103: Invalid separator
  -104: Data type error
  -105: GET not allowed
  -108: Parameter not allowed
  -109: Missing parameter
  -112: Program mnemonic too long
  -113: Undefined header
  -121: Invalid character in number
  -123: Numeric overflow
  -124: Too many digits
  -131: Invalid suffix
  -138: Suffix not allowed
  -148: Character not allowed
  -151: Invalid string data
  -158: String data not allowed
  -160: Block data error
  -161: Block data error
  -162: Block data error
  -163: Block data error
  -164: Block data error
  -165: Block data error
  -166: Block data error
  -167: Block data error
  -168: Block data error
  -170: Expression error
  -171: Expression error
  -172: Expression error
  -173: Expression error
  -174: Expression error
  -175: Expression error
  -176: Expression error
  -177: Expression error
  -178: Expression error
  -211: Trigger ignored
  -213: Init Ignored
  -214: Trigger deadlock
  -221: Settings conflict
  -222: Data out of range
  -223: Too much data
  -224: Illegal parameter value
  -230: Data Stale
  -350: Too many errors
  -410: Query INTERRUPTED
  -420: Query UNTERMINATED
  -430: Query DEADLOCKED
  -440: Query UNTERMINATED after indefinite response
  521: Input buffer overflow
  522: Output buffer overflow
  531: Insufficient memory
  532: Cannot achieve requested resolution
  540: Cannot use overload as math reference
  550: Command not allowed in local
